# Generated by Django 5.0.4 on 2024-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('traits', models.TextField()),
                ('email', models.TextField()),
                ('output', models.TextField()),
            ],
            options={
                'db_table': 'letter_creator',
            },
        ),
    ]
