# Generated by Django 5.0.4 on 2024-05-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalletter',
            name='email',
        ),
        migrations.AlterModelTable(
            name='personalletter',
            table='etter_creator',
        ),
    ]
