# Generated by Django 5.0.4 on 2024-04-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_jobaplicationcreator_jobapplicationcreator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicationCreator',
            new_name='PersonalLetter',
        ),
        migrations.AlterModelTable(
            name='personalletter',
            table='code_letter_creator',
        ),
    ]
