# Generated by Django 5.0.4 on 2024-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personalletter_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalletter',
            name='employer_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalletter',
            name='programming_language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
