# Generated by Django 5.0.4 on 2024-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personalletter_employer_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalletter',
            name='employer_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalletter',
            name='programming_language',
            field=models.TextField(default=''),
        ),
    ]
