# Generated by Django 5.0.4 on 2024-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_personalletter_employer_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalletter',
            name='job_matches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
