# Generated by Django 5.0.4 on 2024-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_personalletter_job_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalletter',
            name='job_matches',
        ),
        migrations.AddField(
            model_name='personalletter',
            name='skill_match',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
