[phases.setup]
nixPkgs = ['...', 'python3']
cmds = [
    "cd backend",
    "python -m venv /opt/venv",
    "source venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[phases.start]
cmd = "sh start.sh"
